# Basic EDA

Looking at each of the tables and asking/answering basic questions.

In [1]:
import datetime
import matplotlib as mpl
import matplotlib.pyplot as plt
import os
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

from src.eda import COLORS, COLORS_DICT, nymyc_cmap, nymyc_cmap_r, read_all_csvs

# mpl.colormaps.register(cmap=nymyc_cmap)
# mpl.colormaps.register(cmap=nymyc_cmap_r)
# nymyc_palette = sns.set_palette(sns.color_palette(COLORS))

# Show all columns in DataFrames
pd.set_option('display.max_columns', None)

# Auto-reload modules
%load_ext autoreload
%autoreload 2

**Read in the data**

In [2]:
%%time
dfs = read_all_csvs('./data')
print(dfs.keys())

[*] Reading in Parks.csv...
[*] Reading in BroadGroups.csv...
[*] Reading in Parks_Properties_20241008.csv...
[*] Reading in 2020_Neighborhood_Tabulation_Areas__NTAs__20241127.csv...
[*] Reading in Mushroom.csv...
[*] Reading in Walks.csv...
[*] Reading in Observations.csv...
dict_keys(['parks', 'broadgroups', 'parks_properties_20241008', '2020_neighborhood_tabulation_areas__ntas__20241127', 'mushroom', 'walks', 'observations'])
CPU times: user 113 ms, sys: 9.01 ms, total: 123 ms
Wall time: 122 ms

In [3]:
for df in list(dfs.keys()):
    print(df.upper())
    display(dfs[df].head())
    print('\n----------\n')

PARKS

   ParkID          ParkName        Borough           City State
0      11   Pelham Bay Park          Bronx  New York City    NY
1      12    High Rock Park  Staten Island  New York City    NY
2      13     Prospect Park       Brooklyn  New York City    NY
3      14  Seton Falls Park          Bronx  New York City    NY
4      15      Kissena Park         Queens  New York City    NY

----------

BROADGROUPS

,BroadGroupID,BroadGroupName,BroadGroupDesc
0,1,Ascomycetes,Ascomycetes are fungi that form sexual spores ...
1,2,Toothed Fungi,Toothed Fungi are a polyphyletic group of Basi...
2,3,Boletes,NaN
3,4,Chanterelles & Allies,NaN
4,5,Coral & Club Fungi,NaN

----------

PARKS_PROPERTIES_20241008

,ACQUISITIONDATE,ACRES,ADDRESS,BOROUGH,CLASS,COMMUNITYBOARD,COUNCILDISTRICT,DEPARTMENT,EAPPLY,GISOBJID,GISPROPNUM,GlobalID,JURISDICTION,LOCATION,MAPPED,NAME311,NYS_ASSEMBLY,NYS_SENATE,OBJECTID,OMPPROPID,PARENTID,PERMIT,PERMITDISTRICT,PERMITPARENT,PIP_RATABLE,PRECINCT,RETIRED,SIGNNAME,SUBCATEGORY,TYPECATEGORY,URL,US_CONGRESS,WATERFRONT,ZIPCODE,Multipolygon
0,1937-06-01,249.389,NaN,Q,PARK,401403404406,1.921222e+09,Q-03,Grand Central Parkway Ext,100000441.0,Q084A,14567485-5E02-4AD0-B8B6-516D78FC8636,DPR/CDOT/SDOT,"Astoria Blvd. and 48 St. to Union Tp., Park Dr...",True,Grand Central Parkway Extension,273536.0,13141516.0,15508,Q084A,Q-03,True,Q-03,Q-03,False,114,False,Grand Central Parkway Extension,EXWY,Parkway,http://www.nycgovparks.org/parks/Q084A/,614.0,True,11103113671136811369113701137111375,MULTIPOLYGON (((-73.8587476480729 40.767414466...
1,1936-12-08,0.327,106 SOUTH 3 STREET,B,PARK,301,3.400000e+01,B-01,Berry Playground,100003860.0,B154,DD571D1C-CB51-4FD2-947F-4619889C6CA4,DPR,S. 3 St. bet. Berry St. and Bedford Ave.,True,Berry Playground,50.0,18.0,5084,B154,B-01,True,B-01,B-01,True,90,False,Berry Playground,Neighborhood Plgd,Playground,http://www.nycgovparks.org/parks/B154/,7.0,False,11211,MULTIPOLYGON (((-73.96319254851623 40.71267695...
2,1935-09-23,2.525,225 NEVINS STREET,B,PARK,306,3.900000e+01,B-06,Thomas Greene Playground,100004507.0,B145,803EA01B-766F-48E0-939F-DC5F4A73BD07,DPR,"Nevins St., 3 Ave., bet. De Graw St. and Dougl...",True,Thomas Greene Playground,52.0,26.0,5083,B145,B-06,True,B-06,B-06,True,78,False,Thomas Greene Playground,Neighborhood Plgd,Community Park,http://www.nycgovparks.org/parks/B145/,10.0,False,11217,MULTIPOLYGON (((-73.98430020422195 40.68021747...
3,1947-12-30,2.836,20 HOUSTON STREET,R,PARK,501,5.000000e+01,R-01,Markham Playground,100004986.0,R076,3483912E-D35D-47E7-8BEA-BC0140025A1A,DPR/DOE,"Willowbrook Pkwy., Forest Ave. to Houston St.",True,Markham Playground,61.0,24.0,5065,R076,R-01,True,R-01,R-01,True,120,False,Markham Playground,JOP,Jointly Operated Playground,http://www.nycgovparks.org/parks/R076/,11.0,False,10302,MULTIPOLYGON (((-74.14513986569457 40.62340561...
4,1955-04-21,3.593,200 ADELAIDE AVENUE,R,PARK,503,5.000000e+01,R-03,Clawson Playground,100004661.0,R072,EB27DEB0-D928-4D42-B907-6A9DE8151275,DPR/DOE,"Adelaide Ave., Clawson St.",False,Clawson Playground,64.0,24.0,5063,R072,R-03,True,R-03,R-03,True,122,False,Clawson Playground,JOP,Jointly Operated Playground,http://www.nycgovparks.org/parks/R072/,11.0,False,10306,MULTIPOLYGON (((-74.12480224365221 40.56108399...

----------

2020_NEIGHBORHOOD_TABULATION_AREAS__NTAS__20241127

,The_geom,BoroCode,BoroName,CountyFIPS,NTA2020,NTAName,NTAAbbrev,NTAType,CDTA2020,CDTAName,Shape_Leng,Shape_Area
0,MULTIPOLYGON (((-73.93213397515774 40.72815960...,3,Brooklyn,47,BK0101,Greenpoint,Grnpt,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28912.566322,3.532121e+07
1,MULTIPOLYGON (((-73.96176070350778 40.72522879...,3,Brooklyn,47,BK0102,Williamsburg,Wllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),28098.027018,2.885431e+07
2,MULTIPOLYGON (((-73.95023693757913 40.70547324...,3,Brooklyn,47,BK0103,South Williamsburg,SWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),18250.280262,1.520896e+07
3,MULTIPOLYGON (((-73.92405909736993 40.71411156...,3,Brooklyn,47,BK0104,East Williamsburg,EWllmsbrg,0,BK01,BK01 Williamsburg-Greenpoint (CD 1 Equivalent),43184.773087,5.226621e+07
4,MULTIPOLYGON (((-73.9923636697722 40.689690123...,3,Brooklyn,47,BK0201,Brooklyn Heights,BkHts,0,BK02,BK02 Downtown Brooklyn-Fort Greene (CD 2 Appro...,14312.504867,9.982322e+06

----------

MUSHROOM

,MushroomID,BroadGroupID,Genus,Species,WhyOrWhyNot,DateCreated,DateModified
0,3,3,Cyanoboletus,pulverulentus,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
1,4,3,Gyroporus,castaneus,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
2,5,3,Tylopilus,ferrugineus,other,2020-04-12 16:53:56,2021-06-24 15:59:48
3,6,3,Xerocomellus,chrysenteron,other,2020-04-12 16:53:56,2021-06-24 19:00:51
4,7,5,Clavulina,cinerea,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56

----------

WALKS

,WalkID,ParkID,WalkDate,WalkDescription,WalkPhoto,DateCreated,DateModified
0,1,19,2009-06-28,This is the first walk for which we have data....,NaN,2023-12-13 21:18:04,2023-12-13 21:18:04
1,2,11,2009-07-11,,NaN,2021-06-24 20:22:14,2021-06-24 20:22:14
2,3,20,2009-07-12,,NaN,2021-08-23 16:32:49,2021-08-23 16:32:49
3,4,19,2010-06-27,,NaN,2022-10-28 14:15:11,2022-10-28 14:15:11
4,5,21,2010-08-07,,NaN,2021-08-10 23:06:38,2021-08-10 23:06:38

----------

OBSERVATIONS

,ObservationID,MushroomID,WalkID,ParkID,NewToPark,NewToCity,Notes,LinkToINat,DateCreated,DateModified
0,1,300,1,19,y,y,as Boletus campestris,NaN,2023-12-11 16:39:21,2023-12-11 16:39:21
1,2,2329,1,19,y,y,NaN,NaN,2023-12-13 21:15:44,2023-12-13 21:15:44
2,3,3,1,19,y,y,(Boletus) pulverulentus,NaN,2023-12-11 16:39:21,2023-12-11 16:39:21
3,4,4,1,19,y,y,NaN,NaN,2023-12-11 16:39:21,2023-12-11 16:39:21
4,5,5,1,19,y,y,NaN,NaN,2023-12-11 16:39:21,2023-12-11 16:39:21

----------

## EDA

Poking around in the data to see what's there, answering some questions that come up.

### Parks

What parks are there? How many per borough?

In [4]:
parks = dfs['parks']
parks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ParkID    34 non-null     int64
 1   ParkName  34 non-null     object
 2   Borough   19 non-null     object
 3   City      29 non-null     object
 4   State     34 non-null     object
dtypes: int64(1), object(4)
memory usage: 1.5+ KB

In [5]:
len(parks.ParkName.unique())

34

What's up with those null Borough and City rows?

In [6]:
parks.loc[parks['Borough'].isna() | parks['City'].isna()]

    ParkID                    ParkName Borough         City State
9       21    Stony Brook, Long Island     NaN          NaN    NY
13      25       Stony Brook, Harriman     NaN   Sloatsburg    NY
16      28          Tallman State Park     NaN    Palisades    NY
18      30                 Beech Brook     NaN          NaN    NY
19      31       Fahnestock State Park     NaN          NaN    NY
20      32  South Mountain Reservation     NaN          NaN    NJ
22      34   Norvin Green State Forest     NaN          NaN    NJ
23      35                  Depew Park     NaN    Peekskill    NY
24      36        Devil's Den Preserve     NaN       Weston    CT
26      38              Mt. Lakes Park     NaN  North Salem    NY
27      39        Wawayanda State Park     NaN       Hewitt    NJ
30      44          Untermeyer Gardens     NaN      Yonkers    NY
31      45   Collis P. Huntingdon Park     NaN      Redding    CT
32      46  Putnam Memorial State Park     NaN      Redding    CT
33      47      Manitou Point Preserve     NaN  Philipstown    NY

So this dataset includes observations from parks outside of NYC. For a first pass at EDA/answering some questions, we should probably drop those.

In [21]:
len(parks.loc[parks['City']=='New York City'])

19

In [7]:
parks.groupby('Borough')['ParkName'].nunique()

Borough
Bronx            4
Brooklyn         2
Manhattan        3
Queens           4
Staten Island    6
Name: ParkName, dtype: int64

In [19]:
parks.loc[parks['ParkName'].str.contains('Cemetery')]

    ParkID             ParkName   Borough           City State
15      27    Woodlawn Cemetery     Bronx  New York City    NY
21      33  Green-Wood Cemetery  Brooklyn  New York City    NY

### Broad Groups

In [8]:
groups = dfs['broadgroups']
groups.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   BroadGroupID    21 non-null     int64
 1   BroadGroupName  21 non-null     object
 2   BroadGroupDesc  7 non-null      object
dtypes: int64(1), object(2)
memory usage: 636.0+ bytes

In [9]:
groups.head()

,BroadGroupID,BroadGroupName,BroadGroupDesc
0,1,Ascomycetes,Ascomycetes are fungi that form sexual spores ...
1,2,Toothed Fungi,Toothed Fungi are a polyphyletic group of Basi...
2,3,Boletes,NaN
3,4,Chanterelles & Allies,NaN
4,5,Coral & Club Fungi,NaN

Some nulls in description, but not necessary to deal with right now.

### Mushrooms

In [10]:
mushrooms = dfs['mushroom']
mushrooms.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1515 entries, 0 to 2130
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   MushroomID    1515 non-null   int64
 1   BroadGroupID  1515 non-null   int64
 2   Genus         1515 non-null   object
 3   Species       1515 non-null   object
 4   WhyOrWhyNot   268 non-null    object
 5   DateCreated   1515 non-null   datetime64[ns]
 6   DateModified  1515 non-null   datetime64[ns]
dtypes: datetime64[ns](2), int64(2), object(3)
memory usage: 94.7+ KB

In [11]:
len(mushrooms.Species.unique())

1308

What is `WhyOrWhyNot`???

In [12]:
mushrooms['WhyOrWhyNot'].value_counts()

WhyOrWhyNot
other                         173
misidentification              11
deprecated                      4
replaced mushroom id 2632.      2
replaced mushroom id 2013.      1
                             ...
replaced mushroom id 2053.      1
replaced mushroom id 834.       1
replaced mushroom id 1156.      1
replaced mushroom id 254.       1
replaced mushroom id 2484.      1
Name: count, Length: 82, dtype: int64

Seems to be some kind of metadata field where the data is altered after the observation event?

In [13]:
mushrooms.head()

,MushroomID,BroadGroupID,Genus,Species,WhyOrWhyNot,DateCreated,DateModified
0,3,3,Cyanoboletus,pulverulentus,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
1,4,3,Gyroporus,castaneus,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
2,5,3,Tylopilus,ferrugineus,other,2020-04-12 16:53:56,2021-06-24 15:59:48
3,6,3,Xerocomellus,chrysenteron,other,2020-04-12 16:53:56,2021-06-24 19:00:51
4,7,5,Clavulina,cinerea,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56

Ethan talked about there being unknown species, represented by `"sp"` or similar. We should find and remove those from the data.

In [14]:
mushrooms['Species'].value_counts()

Species
quercina            6
fragilis            5
marginata           5
americana           5
decipiens           4
                   ..
epiphylla           1
corticium           1
ceres               1
caliciformis        1
coronata-complex    1
Name: count, Length: 1308, dtype: int64

In [15]:
mushrooms.loc[(mushrooms['Species'].str.contains('sp')) | (mushrooms['Species'].str.contains('spp'))]

Empty DataFrame
Columns: [MushroomID, BroadGroupID, Genus, Species, WhyOrWhyNot, DateCreated, DateModified]
Index: []

Tried with `=='sp.'`, but `.str.contains('sp.')` captures a few other odd ones, like `"sp-NY09"` that we definitely don't want in there. Going to add this to the `clean_data()` logic in `eda.py`.

In [16]:
mushrooms.loc[mushrooms['Species']!='sp']

,MushroomID,BroadGroupID,Genus,Species,WhyOrWhyNot,DateCreated,DateModified
0,3,3,Cyanoboletus,pulverulentus,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
1,4,3,Gyroporus,castaneus,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
2,5,3,Tylopilus,ferrugineus,other,2020-04-12 16:53:56,2021-06-24 15:59:48
3,6,3,Xerocomellus,chrysenteron,other,2020-04-12 16:53:56,2021-06-24 19:00:51
4,7,5,Clavulina,cinerea,NaN,2020-04-12 16:53:56,2020-04-12 16:53:56
...,...,...,...,...,...,...,...
2126,3211,1,Phyllachora,graminis,NaN,2024-11-21 07:23:34,2024-11-21 07:23:34
2127,3212,15,Comatricha,nigra,NaN,2024-11-21 07:23:34,2024-11-21 07:23:34
2128,3213,13,Phragmidium,rubi-idaei,NaN,2024-11-21 07:23:34,2024-11-21 07:23:34
2129,3214,13,Puccinia,coronata-complex,NaN,2024-11-21 07:23:34,2024-11-21 07:23:34
2130,3215,13,Puccionia,violae,NaN,2024-11-21 07:23:34,2024-11-21 07:23:34

In [17]:
print('All rows: ', mushrooms.shape)
print('Rows to drop: ', mushrooms.loc[(mushrooms['Species'].str.contains('sp.')) | (mushrooms['Species'].str.contains('spp.'))].shape)
print('Rows to keep: ', mushrooms.loc[(~mushrooms['Species'].str.contains('sp.')) & (~mushrooms['Species'].str.contains('spp.'))].shape)

All rows:  (1515, 7)
Rows to drop:  (0, 7)
Rows to keep:  (1515, 7)

How many mushrooms are there per broad group?

In [18]:
pd.DataFrame(mushrooms.merge(groups, on='BroadGroupID', how='left').groupby('BroadGroupName')['MushroomID'].nunique())

                       MushroomID
BroadGroupName
Ascomycetes                   334
Atractiellomycetes              2
Boletes                       104
Chanterelles & Allies          12
Chytridiomycota                 2
Coral & Club Fungi             26
Crusts & Parchment            103
Cyphelloid Fungi                5
Dimorphic Fungi                 1
Fiber Fans & Vases              5
Gasteromycetes                 37
Gilled Fungi                  564
Jelly Fungi                    20
Lichens                        51
Myxomycetes                    59
Oomycetes                       3
Polypores                     125
Rusts                          34
Smuts                           1
Toothed Fungi                  23
Zygomycetes                     4

## Research Questions

The following questions come from the draft report.

### Common
 - **What are the most common fungi in the city (by form group)?**
 - Which fungi do we see in almost every park?
 - Are any species localized to one or two parks?
 - What are the most common fungi per season?
 - **What fungi is consistently seen all year long?**

### Rare
 - What discoveries were shocking or noteable? (Ex: first ones found, rare fungi, fungi in atypical location)
 - What’s the rarest species in the city, by form group?
 - **Which parks are the most fungally diverse?** 

### New
 - At what rate are we adding new species to our lists? 

### Observations per Species
 - What’s been seen? Where?
 - Are there species that are becoming more common? 
 - **Is anything on a decline / are there any species becoming observed less frequently?**

### Additional ideas:
 - What’s the most common fungi per borough?
 - **How does NYC compare with other urban areas (using iNat data) - either in reporting style or actual species?**
 - How do temperature impact discoveries (bringing in temperature data for each walk)?
 - Controlling for above biases, what locations and seasons show the most abundance?
 - Are there potential environmental factors, like substrate or surrounding environment, within parks that correlate with higher fungal diversity or specific fungi? (Might need to work with a local expert on this)
 - Could we profile some of the people that make it all happen?
 - Could we profile some of our most interesting discoveries?